<a href="https://colab.research.google.com/github/SakshamSingh5224/Tools-/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas numpy

In [ ]:
import numpy as np


In [ ]:

a = np.array([1,2,3,4], dtype='int32')
print(a)
print(a[2]+a[3])

[1 2 3 4]
7


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:

# Get Dimension
a.ndim

1

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Get Type
a.dtype

dtype('int32')

In [ ]:
# Get Size
a.itemsize

4

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
array=np.array([1,2,3,4])
array=array*2
print(array)
print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


In [ ]:
array=np.array([['A','B','C'],
 ['D','E','F'],
  ['G','H',"I"]])
print(array.ndim)
print(array[0,1])
word=array[0,0]+array[1,1]
print(word)

2
B
AE


In [ ]:
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

print(array[:,0])

[ 1  5  9 13]


In [ ]:
#Scalar Arithmetic
array=np.array([1,2,3])
print(array+1)
print(array-2)
print(array*3)
print(array/4)
print(array**5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
#Vectorized math funcs

print(np.sqrt(array))
print(np.round(array))
print(np.ceil(array))
print(np.pi)

[1.         1.41421356 1.73205081]
[1 2 3]
[1. 2. 3.]
3.141592653589793


In [ ]:
radii=np.array([1,2,3])
print(np.pi*(radii**2))

[ 3.14159265 12.56637061 28.27433388]


In [ ]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
print(array1**array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
scores=np.array([91,55,100,73,82,64])
print(scores>=60)
scores[scores<60]=0
print(scores)

[ True False  True  True  True  True]
[ 91   0 100  73  82  64]


In [ ]:
# Broadcasting allows NumPy to perform operations on arrays
# with different shapes by virtually expanding dimensions
# so they match the larger array's shape.

# The dimensions have the same size
# OR
# One of the dimensions has a size of 1.

In [ ]:
array1=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
array2=np.array([[1,2],[2,3],[3,4],[4,5]])
print(array1.shape)
print(array2.shape)



(4, 4)
(4, 2)


In [ ]:
array1=np.array([[1,2,3,4,5,6,7,8,9,10]])
array2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1.shape)
print(array2.shape)

print(array1*array2)


(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
# Aggregate functions = summarize data and typically return a single value


In [ ]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.median(array))
print(np.sum(array,axis=0))
print(np.sum(array,axis=1))

55
5.5
2.8722813232690143
8.25
1
10
0
9
5.5
[ 7  9 11 13 15]
[15 40]


In [ ]:
# Filtering = Refers to the process of selecting elements from
# an array that match a given condition

In [ ]:
ages=np.array([[21,17,19,20,16,30,18,65],
               [39,22,15,99,18,19,20,21]])

teenagers = ages[ages<18]
print(teenagers)
adults=ages[(ages>=18)&(ages<65)]
print(adults)
adults=ages[(ages<18) | (ages>=65)]
print(adults)

seniors=ages[ages>=65]
print(seniors)



[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[17 16 65 15 99]
[65 99]


In [ ]:
adults=np.where(ages>=18,ages,0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [ ]:
rng=np.random.default_rng(seed=1)
print(rng.integers(low=1,high=101,size=(3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [ ]:
np.random.seed(seed=1)
print(np.random.uniform(low=-1,high=1,size=(3,2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [ ]:
rng=np.random.default_rng()
array=np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[1 5 4 2 3]


In [ ]:
rng=np.random.default_rng()

fruits=np.array(['apple','banana','cherry','durian','elderberry'])
fruits=rng.choice(fruits,size=(3,3))
print(fruits)

[['durian' 'durian' 'cherry']
 ['apple' 'apple' 'apple']
 ['cherry' 'cherry' 'apple']]
