<a href="https://colab.research.google.com/github/SakshamSingh5224/Tools-/blob/main/Pandas_Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import NumPy (the standard convention is to alias it as 'np')
import numpy as np

print(f"NumPy version: {np.__version__}")
# Output: NumPy version: 1.26.0 (or whatever your current version is)

NumPy version: 2.0.2


In [ ]:
# Standard Python List: Multiplying every number by 2 requires a loop
my_list = [1, 2, 3, 4, 5]
list_result = [x * 2 for x in my_list]
print("Python List Result:", list_result)
# Output: Python List Result: [2, 4, 6, 8, 10]

# NumPy Array: You can multiply the whole array at once (Vectorization)
my_array = np.array([1, 2, 3, 4, 5])
array_result = my_array * 2
print("NumPy Array Result:", array_result)
# Output: NumPy Array Result: [ 2  4  6  8 10]

Python List Result: [2, 4, 6, 8, 10]
NumPy Array Result: [ 2  4  6  8 10]


In [ ]:
# 1. From a regular Python list
temp_data = np.array([72.5, 74.1, 79.8, 81.2])

# 2. An array of all zeros (great for placeholders)
# The tuple (3, 4) means 3 rows, 4 columns
zeros_grid = np.zeros((3, 4))
print("Zeros:\n", zeros_grid)

# 3. Generating a sequence of numbers (Start, Stop-exclusive, Step)
sequence = np.arange(0, 10, 2)
print("\nArange:", sequence)
# Output: [0 2 4 6 8]

# 4. Generating evenly spaced numbers (Start, Stop-inclusive, Number of items)
spaced = np.linspace(0, 1, 5)
print("\nLinspace:", spaced)
# Output: [0.   0.25 0.5  0.75 1.  ]

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Arange: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Let's create a 2D array (a matrix)
matrix = np.array([[1.5, 2.0, 3.1],
                   [4.2, 5.5, 6.8]])

print("Shape (rows, columns):", matrix.shape)
# Output: (2, 3)

print("Number of Dimensions:", matrix.ndim)
# Output: 2

print("Data Type:", matrix.dtype)
# Output: float64

Shape (rows, columns): (2, 3)
Number of Dimensions: 2
Data Type: float64


In [ ]:
# We will use the matrix from the previous step
print("Original Matrix:\n", matrix)

# Grab the element in row 0, column 1
print("\nSpecific Element:", matrix[0, 1])
# Output: 2.0

# Grab the entire first row
print("\nFirst Row:", matrix[0, :])
# Output: [1.5 2.  3.1]

# Grab the entire last column
print("\nLast Column:", matrix[:, -1])
# Output: [3.1 6.8]

Original Matrix:
 [[1.5 2.  3.1]
 [4.2 5.5 6.8]]

Specific Element: 2.0

First Row: [1.5 2.  3.1]

Last Column: [3.1 6.8]


In [ ]:
sales = np.array([100, 150, 200, 50])

# Math operations apply to every element
taxes = sales * 0.05
print("Taxes:", taxes)
# Output: [ 5.   7.5 10.   2.5]

# Aggregation functions
print("Total Sales:", np.sum(sales))     # Output: 500
print("Average Sales:", np.mean(sales))   # Output: 125.0
print("Max Sale:", np.max(sales))         # Output: 200

Taxes: [ 5.   7.5 10.   2.5]
Total Sales: 500
Average Sales: 125.0
Max Sale: 200


In [ ]:
# 2D array of student scores (3 students, 2 subjects)
scores = np.array([[85, 90],
                   [78, 88],
                   [92, 95]])

# 1D array of extra credit points per subject
extra_credit = np.array([5, 2])

# NumPy automatically "broadcasts" the 1D array across every row of the 2D array
final_grades = scores + extra_credit

print("Final Grades:\n", final_grades)
# Output:
# [[ 90  92]
#  [ 83  90]
#  [ 97  97]]

Final Grades:
 [[90 92]
 [83 90]
 [97 97]]


In [ ]:
ages = np.array([15, 22, 17, 35, 12, 40])

# Create a "mask" of True/False values
is_adult = ages >= 18
print("Mask:", is_adult)
# Output: [False  True False  True False  True]

# Apply the mask to the original array to filter it
adult_ages = ages[is_adult]

# Shortcut: ages[ages >= 18]
print("Filtered Ages:", adult_ages)
# Output: [22 35 40]

Mask: [False  True False  True False  True]
Filtered Ages: [22 35 40]


In [ ]:
# 1. Create a 3x3 array of random numbers between 0 and 1
np.random.seed(42) # Set seed for reproducibility
random_grid = np.random.rand(3, 3)
print("Original Grid:\n", random_grid)

# 2. Replace numbers greater than 0.5 with 1
random_grid[random_grid > 0.5] = 1.0

print("\nModified Grid:\n", random_grid)

Original Grid:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Modified Grid:
 [[0.37454012 1.         1.        ]
 [1.         0.15601864 0.15599452]
 [0.05808361 1.         1.        ]]


In [ ]:
# Pandas Tutorial
# The standard convention is to import pandas as 'pd'
import pandas as pd
import numpy as np

print(f"Pandas version: {pd.__version__}")
# Output: Pandas version: 2.1.0 (or your current version)

Pandas version: 2.2.2


In [ ]:
# Creating a Series (1D)
ages = pd.Series([25, 30, 35, 40], name="Age")
print(ages)
# Output:
# 0    25
# 1    30
# 2    35
# 3    40
# Name: Age, dtype: int64

# Creating a DataFrame (2D) from a Python dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana"],
    "Age": [25, 30, 35, 40],
    "City": ["New York", "Paris", "London", "Tokyo"],
    "Salary": [70000, 80000, 120000, 95000]
}
df = pd.DataFrame(data)
print("\nDataFrame:\n", df)

0    25
1    30
2    35
3    40
Name: Age, dtype: int64

DataFrame:
       Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30     Paris   80000
2  Charlie   35    London  120000
3    Diana   40     Tokyo   95000


In [ ]:
# How to load data (Theoretical example for your readers)
# df = pd.read_csv("my_dataset.csv")

# 1. View the first 2 rows
print(df.head(2))

# 2. Get a technical summary of the DataFrame (non-null counts, data types)
print("\nInfo:")
df.info()

# 3. Get statistical summaries of numerical columns (mean, min, max, etc.)
print("\nDescribe:\n", df.describe())

    Name  Age      City  Salary
0  Alice   25  New York   70000
1    Bob   30     Paris   80000

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   City    4 non-null      object
 3   Salary  4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

Describe:
              Age         Salary
count   4.000000       4.000000
mean   32.500000   91250.000000
std     6.454972   21746.647251
min    25.000000   70000.000000
25%    28.750000   77500.000000
50%    32.500000   87500.000000
75%    36.250000  101250.000000
max    40.000000  120000.000000


In [ ]:
# --- SELECTING COLUMNS ---
# Select a single column (returns a Series)
cities = df["City"]
print("Cities:\n", cities)
# Output:
# 0      New York
# 1        Paris
# 2      London
# 3      Tokyo
# Name: City, dtype: object

# Select multiple columns (returns a DataFrame - note the double brackets!)
name_and_salary = df[["Name", "Salary"]]
print("\nName and Salary:\n", name_and_salary)


# --- SELECTING ROWS ---
# Pandas uses .iloc (integer location) and .loc (label location)

# Grab the very first row using its index position (0)
first_person = df.iloc[0]
print("First person's data:\n", first_person)
# Output:
# Name         Alice
# Age             25
# City      New York
# Salary       70000

Cities:
 0    New York
1       Paris
2      London
3       Tokyo
Name: City, dtype: object

Name and Salary:
       Name  Salary
0    Alice   70000
1      Bob   80000
2  Charlie  120000
3    Diana   95000
First person's data:
 Name         Alice
Age             25
City      New York
Salary       70000
Name: 0, dtype: object


In [ ]:
# Find everyone who makes more than 85,000
high_earners_mask = df["Salary"] > 85000
high_earners = df[high_earners_mask]

# Shortcut (how it is usually written in practice):
# high_earners = df[df["Salary"] > 85000]

print("High Earners:\n", high_earners)
# Output:
#       Name  Age    City  Salary
# 2  Charlie   35  London  120000
# 3    Diana   40   Tokyo   95000

# Multiple conditions: Use & (and), | (or) inside parentheses
specific_people = df[(df["Age"] < 35) & (df["City"] == "New York")]

High Earners:
       Name  Age    City  Salary
2  Charlie   35  London  120000
3    Diana   40   Tokyo   95000


In [ ]:
# Let's introduce some missing data deliberately
df.loc[1, "Salary"] = np.nan
print("Data with missing value:\n", df)

# Option A: Drop any rows that have missing data
clean_df = df.dropna()

# Option B: Fill the missing data with a specific value (e.g., the average salary)
avg_salary = df["Salary"].mean()
filled_df = df.fillna({"Salary": avg_salary})

print("\nData after filling missing value:\n", filled_df)

Data with missing value:
       Name  Age      City    Salary
0    Alice   25  New York   70000.0
1      Bob   30     Paris       NaN
2  Charlie   35    London  120000.0
3    Diana   40     Tokyo   95000.0

Data after filling missing value:
       Name  Age      City    Salary
0    Alice   25  New York   70000.0
1      Bob   30     Paris   95000.0
2  Charlie   35    London  120000.0
3    Diana   40     Tokyo   95000.0


In [ ]:
# Create a new column by doing math on an existing one
filled_df["Bonus"] = filled_df["Salary"] * 0.10

# Create a new column based on a condition using np.where
# Syntax: np.where(condition, value_if_true, value_if_false)
filled_df["Seniority"] = np.where(filled_df["Age"] >= 35, "Senior", "Junior")

print(filled_df)

      Name  Age      City    Salary    Bonus Seniority
0    Alice   25  New York   70000.0   7000.0    Junior
1      Bob   30     Paris   95000.0   9500.0    Junior
2  Charlie   35    London  120000.0  12000.0    Senior
3    Diana   40     Tokyo   95000.0   9500.0    Senior


In [ ]:
# Let's add one more person to make grouping more interesting
new_row = pd.DataFrame([{"Name": "Eve", "Age": 28, "City": "London", "Salary": 85000, "Bonus": 8500, "Seniority": "Junior"}])
final_df = pd.concat([filled_df, new_row], ignore_index=True)

# Group by the 'City' column and find the average salary in each city
city_salaries = final_df.groupby("City")["Salary"].mean()

print("\nAverage Salary by City:\n", city_salaries)
# Output:
# City
# London      102500.0
# New York     70000.0
# Paris        94000.0  (Assuming Paris was filled with the mean earlier)
# Tokyo        95000.0


Average Salary by City:
 City
London      102500.0
New York     70000.0
Paris        95000.0
Tokyo        95000.0
Name: Salary, dtype: float64
